# Generated by Django 6.0.6 on 2026-06-09 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='quantity',
            new_name='stock',
        ),
    ]
